language: ruby
rvm:
  - 2.0.0
gemfile:
  - gemfiles/rails-3.2.x.gemfile
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "K6ImpyANeGx3jSw6keDTZztfVm+bpBMbBgDPQHfGGKH80HoB28kjXLlKh2EF\nuhielkw+tPGX94TkPq+nAtaCx4771hpzFqGXtsXba//oGnoGPzbApOILTXs6\nqkxsHCEQK+8i1b0hpQeZREo+Mk4G7q5Mkel4+Jf12CInahlGh+o="
