version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: bkuhlmann/alpine-ruby:latest
        environment:
          PGHOST: localhost
          PGUSER: test
          RAILS_ENV: test
      - image: postgres:latest
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: dummy_test
          POSTGRES_PASSWORD: test
    steps:
      - checkout

      - restore_cache:
          name: Bundler Restore
          keys:
            - gem-cache-{{.Branch}}-{{checksum "prawn_plus.gemspec"}}
            - gem-cache-

      - run:
          name: Bundler Install
          command: |
            gem update --system
            bundle config set path "vendor/bundle"
            bundle install

      - save_cache:
          name: Bundler Store
          key: gem-cache-{{.Branch}}-{{checksum "prawn_plus.gemspec"}}
          paths:
            - vendor/bundle

      - run:
          name: Build
          command: |
            sed -i 's/ rubycritic//g' Rakefile
            bundle exec rake
